export const GET_DOGS = "GET_DOGS";
export const GET_DETAIL= "GET_DETAIL"

export const ORDER_BY_NAME="ORDER_BY_NAME"
export const ORDER_WEIGHT="ORDER_WEIGHT"

export const FILTER_CREATED = "FILTER_CREATED"
export const FILTER_BY_TEMPERAMENT="FILTER_BY_TEMPERAMENT"